# 개발 서버
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/kickrush_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # data:
  #   redis:
  #     host: ${REDIS_HOST:localhost}
  #     port: 6379

logging:
  level:
    com.kanga: DEBUG