# 운영 서버 
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/kickrush
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  # data:
  #   redis:
  #     host: ${REDIS_HOST}
  #     port: 6379

logging:
  level:
    root: WARN
    com.kanga: INFO