# 테스트 
spring:
  datasource:
    url: jdbc:h2:mem:kickrush-test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379

logging:
  level:
    root: WARN
    com.kanga: INFO